### ISSUE TITLE
Add optional boundaries (min, max)

### ISSUE THREAD

**Issue by drivardxrm** [drivardxrm/Sparkline.PCF#10]
based on this discussion, need to add optional min and max
----------------------------

How do you set the vertical axis minimum value?

Consider you are plotting a bar chart with the following data points:
- 4000
- 4000
- 3900

The 3900 looks like it's 0. This is the same issue you get with Excel sparklines but Excel allows you to set the vertical axis minimum value to 0 to resolve the issue. See example here:
https://trumpexcel.com/sparklines/

_Originally posted by @sam9090 in https://github.com/drivardxrm/Sparkline.PCF/discussions/9_

**Comment by sam9090** [comment]
Thanks David, great news that you will enhance it. It's a great little tool, I'm keen to use it on a financial summary tab to add some visuals under the numbers.

**Comment by drivardxrm** [comment]
@sam9090 I have released a new version that gives you the possibility to add boundaries (min and max)
[latest release](https://github.com/drivardxrm/Sparkline.PCF/releases/latest)

**Comment by sam9090** [comment]
Just install it and it's working beautifully, thanks David. It makes for some fine finishing touches on a form.
Sam
